In [168]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [169]:
turns = pd.read_csv("turns.csv")
turns

,game_id,turn_number,nickname,rack,location,move,points,score,turn_type
0,1,1,BetterBot,DDEGITT,8G,DIG,10,10,Play
1,1,2,stevy,AEHOPUX,7H,HAP,18,18,Play
2,1,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play
3,1,4,stevy,EMORSUX,5K,UM,16,34,Play
4,1,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play
...,...,...,...,...,...,...,...,...,...
2005493,72773,22,adola,ABINRRU,15N,IN,18,376,Play
2005494,72773,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play
2005495,72773,24,adola,ABRRU,15E,BRA.,7,383,Play
2005496,72773,25,HastyBot,EIP,7A,PIE,11,342,Play
2005497,72773,26,HastyBot,NaN,NaN,(RU),4,346,End

In [170]:
turns.columns

Index(['game_id', 'turn_number', 'nickname', 'rack', 'location', 'move',
       'points', 'score', 'turn_type'],
      dtype='object')

In [171]:
games = pd.read_csv("games.csv")
games

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274
1,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418
2,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262
3,4,BetterBot,regular,RESIGNED,0,2022-09-12 02:36:19,CSW21,3600,0,CASUAL,1,350.861141
4,5,STEEBot,regular,STANDARD,0,2022-09-06 04:31:36,NWL20,1200,0,CASUAL,1,642.688722
...,...,...,...,...,...,...,...,...,...,...,...,...
72768,72769,browndav,blitz,STANDARD,0,2022-09-07 13:24:13,CSW21,180,0,RATED,1,218.043751
72769,72770,HastyBot,regular,TIME,0,2022-09-04 00:13:24,CSW21,3600,0,RATED,1,3662.659287
72770,72771,HastyBot,regular,STANDARD,0,2022-09-19 03:28:44,ECWL,900,0,CASUAL,10,236.133634
72771,72772,Gtowngrad,regular,STANDARD,0,2022-08-31 15:57:38,NWL20,900,0,RATED,1,681.370077
72772,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262

In [172]:
games.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds'],
      dtype='object')

In [173]:
games_turns_merged = pd.merge(games, turns, on=["game_id"], how="left")

In [174]:
games_turns_merged.shape

(2005498, 20)

In [175]:
games_turns_merged.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds',
       'turn_number', 'nickname', 'rack', 'location', 'move', 'points',
       'score', 'turn_type'],
      dtype='object')

In [176]:
games_turns_merged.drop_duplicates()

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score,turn_type
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End

In [177]:
games_turns_merged.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds',
       'turn_number', 'nickname', 'rack', 'location', 'move', 'points',
       'score', 'turn_type'],
      dtype='object')

In [178]:
games_turns_merged.isnull().sum()

game_id                       0
first                         0
time_control_name             0
game_end_reason               0
winner                        0
created_at                    0
lexicon                       0
initial_time_seconds          0
increment_seconds             0
rating_mode                   0
max_overtime_minutes          0
game_duration_seconds         0
turn_number                   0
nickname                      0
rack                      69390
location                 132239
move                        454
points                        0
score                         0
turn_type                   395
dtype: int64

In [179]:
games_turns_merged

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score,turn_type
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End

In [180]:
train = pd.read_csv('train.csv')
train

        game_id        nickname  score  rating
0             1       BetterBot    335    1637
1             1           stevy    429    1500
2             3       davidavid    440    1811
3             3       BetterBot    318    2071
4             4  Inandoutworker    119    1473
...         ...             ...    ...     ...
100815    72771        HastyBot    393    1614
100816    72772       BetterBot    442    1674
100817    72772       Gtowngrad    388    1364
100818    72773           adola    383    2075
100819    72773        HastyBot    346    2302

[100820 rows x 4 columns]

In [181]:
test = pd.read_csv('test.csv')
test

       game_id    nickname  score  rating
0            2       Super    488     NaN
1            2   BetterBot    401  2000.0
2            7     STEEBot    377  2082.0
3            7      Priya1    379     NaN
4           11     STEEBot    334  1829.0
...        ...         ...    ...     ...
44721    72762   kyjo55555    367     NaN
44722    72768    HastyBot    524  2356.0
44723    72768  Maximilian    357     NaN
44724    72769     STEEBot    626  2110.0
44725    72769    browndav    384     NaN

[44726 rows x 4 columns]

In [182]:
train_test_merge = pd.merge(train, test, how="outer", on = ["game_id", "nickname"])

In [183]:
train_test_merge

        game_id        nickname  score_x  rating_x  score_y  rating_y
0             1       BetterBot    335.0    1637.0      NaN       NaN
1             1           stevy    429.0    1500.0      NaN       NaN
2             3       davidavid    440.0    1811.0      NaN       NaN
3             3       BetterBot    318.0    2071.0      NaN       NaN
4             4  Inandoutworker    119.0    1473.0      NaN       NaN
...         ...             ...      ...       ...      ...       ...
145541    72762       kyjo55555      NaN       NaN    367.0       NaN
145542    72768        HastyBot      NaN       NaN    524.0    2356.0
145543    72768      Maximilian      NaN       NaN    357.0       NaN
145544    72769         STEEBot      NaN       NaN    626.0    2110.0
145545    72769        browndav      NaN       NaN    384.0       NaN

[145546 rows x 6 columns]

In [184]:
train_test_merge['score_x'].fillna(train_test_merge['score_y'], inplace=True)
train_test_merge['rating_x'].fillna(train_test_merge['rating_y'], inplace=True)

# Drop the redundant columns
train_test_merge.drop(['score_y', 'rating_y'], axis=1, inplace=True)

# Rename the columns if needed
train_test_merge.rename(columns={'score_x': 'score', 'rating_x': 'rating'}, inplace=True)

In [185]:
train_test_merge

        game_id        nickname  score  rating
0             1       BetterBot  335.0  1637.0
1             1           stevy  429.0  1500.0
2             3       davidavid  440.0  1811.0
3             3       BetterBot  318.0  2071.0
4             4  Inandoutworker  119.0  1473.0
...         ...             ...    ...     ...
145541    72762       kyjo55555  367.0     NaN
145542    72768        HastyBot  524.0  2356.0
145543    72768      Maximilian  357.0     NaN
145544    72769         STEEBot  626.0  2110.0
145545    72769        browndav  384.0     NaN

[145546 rows x 4 columns]

In [186]:
games_turns_merged_train = pd.merge(games_turns_merged, train, how="left", on = ["game_id", "nickname"])

In [187]:
games_turns_merged_train

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0

In [188]:
data = games_turns_merged_train

In [189]:
game1 = data[data['game_id'] == 72773]

In [190]:
game1

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating
2005472,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,1,HastyBot,ACELOOX,8D,COXAL,34,34,Play,346.0,2302.0
2005473,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,2,adola,AADEETY,7G,YEAD,24,24,Play,383.0,2075.0
2005474,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,3,HastyBot,?DEEMOQ,J2,QuEME.,39,73,Play,346.0,2302.0
2005475,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,4,adola,AADEORT,K5,AD,17,41,Play,383.0,2075.0
2005476,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,5,HastyBot,DDILNOO,9E,DID,28,101,Play,346.0,2302.0
2005477,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,6,adola,AEOORTZ,L1,ZOOEA,53,94,Play,383.0,2075.0
2005478,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,7,HastyBot,ELNOOTT,1L,.OOT,39,140,Play,346.0,2302.0
2005479,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,8,adola,?EEFNRT,M3,FERmENT,90,184,Play,383.0,2075.0
2005480,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,9,HastyBot,EHILNST,8K,NI.TH,27,167,Play,346.0,2302.0
2005481,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,10,adola,ACEGLOU,4D,CAGOUL.,22,206,Play,383.0,2075.0
2005482,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,11,HastyBot,BELSUWW,E3,W.W,18,185,Play,346.0,2302.0
2005483,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,12,adola,AEFNNRS,10B,FANES,34,240,Play,383.0,2075.0
2005484,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,13,HastyBot,BEKLSUV,6C,BULK,30,215,Play,346.0,2302.0
2005485,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,14,adola,NNORSTT,G2,TR.N,5,245,Play,383.0,2075.0
2005486,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,15,HastyBot,EIISTVV,10I,VIVES,23,238,Play,346.0,2302.0
2005487,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,16,adola,IJNOPST,C9,J.,17,262,Play,383.0,2075.0
2005488,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,17,HastyBot,AGIITUY,11B,AYU,26,264,Play,346.0,2302.0
2005489,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,18,adola,INOPSST,12D,SPINTOS,76,338,Play,383.0,2075.0
2005490,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,19,HastyBot,GIIIORT,13J,TORII,12,276,Play,346.0,2302.0
2005491,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,20,adola,EILMRRU,12L,ELM,20,358,Play,383.0,2075.0
2005492,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,21,HastyBot,AEEGIIR,14K,EAGRE,31,307,Play,346.0,2302.0
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0

In [191]:
cols = 'time_control_name', 'game_end_reason', 'lexicon', 'rating_mode', 'turn_type'

In [192]:
for c in cols:
    print(data[c].value_counts())

regular       1663015
rapid          183524
blitz          124420
ultrablitz      34539
Name: time_control_name, dtype: int64
STANDARD              1884994
RESIGNED                56587
TIME                    53954
CONSECUTIVE_ZEROES       9963
Name: game_end_reason, dtype: int64
CSW21     1224851
NWL20      584671
ECWL       195866
NSWL20        110
Name: lexicon, dtype: int64
RATED     1478679
CASUAL     526819
Name: rating_mode, dtype: int64
Play             1872864
End                67987
Exchange           48997
Pass                8065
Timeout             4143
Challenge           2571
Six-Zero Rule        476
Name: turn_type, dtype: int64

### Count turns number by game_id and nickname

In [193]:
turns_count = data[data['turn_type'] != 'End'].groupby(['game_id', 'nickname'])['turn_number'].count().reset_index()
turns_count.rename(columns={'turn_number': 'turns_count'}, inplace=True)
turns_count

        game_id   nickname  turns_count
0             1  BetterBot           13
1             1      stevy           13
2             2  BetterBot           12
3             2      Super           13
4             3  BetterBot           13
...         ...        ...          ...
145541    72771   HastyBot           15
145542    72772  BetterBot           14
145543    72772  Gtowngrad           15
145544    72773   HastyBot           13
145545    72773      adola           12

[145546 rows x 3 columns]

### Count max points by game_id and nickname

In [194]:
max_point = data.groupby(['game_id', 'nickname'])['points'].max().reset_index()
max_point.rename(columns={'points': 'max_point'}, inplace=True)
max_point

        game_id   nickname  max_point
0             1  BetterBot         68
1             1      stevy         98
2             2  BetterBot         85
3             2      Super         94
4             3  BetterBot         76
...         ...        ...        ...
145541    72771   HastyBot         93
145542    72772  BetterBot         81
145543    72772  Gtowngrad         67
145544    72773   HastyBot         39
145545    72773      adola         90

[145546 rows x 3 columns]

### Count min points by game_id and nickname

In [195]:
min_point = data.groupby(['game_id', 'nickname'])['points'].min().reset_index()
min_point.rename(columns={'points': 'min_point'}, inplace=True)
min_point

        game_id   nickname  min_point
0             1  BetterBot          8
1             1      stevy          2
2             2  BetterBot          8
3             2      Super          0
4             3  BetterBot          0
...         ...        ...        ...
145541    72771   HastyBot          0
145542    72772  BetterBot          9
145543    72772  Gtowngrad          4
145544    72773   HastyBot          4
145545    72773      adola          5

[145546 rows x 3 columns]

In [196]:
data_merge = pd.merge(turns_count, max_point, on=["game_id", 'nickname'], how="inner")

In [197]:
data_merge = pd.merge(data_merge, min_point, on=["game_id", 'nickname'], how="inner")

In [198]:
data_merge

        game_id   nickname  turns_count  max_point  min_point
0             1  BetterBot           13         68          8
1             1      stevy           13         98          2
2             2  BetterBot           12         85          8
3             2      Super           13         94          0
4             3  BetterBot           13         76          0
...         ...        ...          ...        ...        ...
145541    72771   HastyBot           15         93          0
145542    72772  BetterBot           14         81          9
145543    72772  Gtowngrad           15         67          4
145544    72773   HastyBot           13         39          4
145545    72773      adola           12         90          5

[145546 rows x 5 columns]

### Count number of bingo and average word length by game_id and nickname

In [199]:
data['word_len'] = data.apply(lambda row: len(str(row['move']).replace('.', '')) if row['turn_type'] == 'Play' else 0, axis=1)
data

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0,3
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0,3
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0,4
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0,2
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0,2
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0,3
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0,3
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0,3
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0,0

In [200]:
data['bingo'] = data['word_len'].apply(lambda x: 1 if x == 7 else 0)

In [201]:
avg_bingo = data.groupby(['game_id', 'nickname'])['bingo'].mean().reset_index()
avg_bingo.rename(columns={'bingo': 'avg_bingo'}, inplace=True)
avg_bingo

        game_id   nickname  avg_bingo
0             1  BetterBot   0.076923
1             1      stevy   0.142857
2             2  BetterBot   0.250000
3             2      Super   0.214286
4             3  BetterBot   0.076923
...         ...        ...        ...
145541    72771   HastyBot   0.133333
145542    72772  BetterBot   0.142857
145543    72772  Gtowngrad   0.125000
145544    72773   HastyBot   0.000000
145545    72773      adola   0.166667

[145546 rows x 3 columns]

In [202]:
avg_word_len = data.groupby(['game_id', 'nickname'])['word_len'].mean().reset_index()
avg_word_len

        game_id   nickname  word_len
0             1  BetterBot  4.000000
1             1      stevy  3.357143
2             2  BetterBot  4.250000
3             2      Super  3.428571
4             3  BetterBot  3.538462
...         ...        ...       ...
145541    72771   HastyBot  3.333333
145542    72772  BetterBot  3.785714
145543    72772  Gtowngrad  2.812500
145544    72773   HastyBot  3.571429
145545    72773      adola  4.000000

[145546 rows x 3 columns]

### Count letter JQXZ by game_id and nickname

In [203]:
letters_to_count = ['J', 'Q', 'X', 'Z']

for letter in letters_to_count:
    data[f'{letter}_count'] = data[data['turn_type'] == 'Play']['move'].apply(lambda x: str(x).count(letter) if pd.notna(x) else 0)

In [204]:
data['total_count'] = data.apply(lambda row: sum(row[f'{letter}_count'] for letter in letters_to_count), axis=1)

In [205]:
data

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0,3,0,0.0,0.0,0.0,0.0,0.0
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0,4,0,0.0,0.0,0.0,0.0,0.0
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0,6,0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0,2,0,0.0,0.0,0.0,0.0,0.0
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0,3,0,0.0,0.0,0.0,0.0,0.0
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0,0,0,NaN,NaN,NaN,NaN,NaN

In [206]:
special_letter = data.groupby(['game_id', 'nickname'])['total_count'].sum().reset_index()
special_letter.rename(columns={'total_count': 'count_letters_JQXZ'}, inplace=True)
special_letter

        game_id   nickname  count_letters_JQXZ
0             1  BetterBot                 3.0
1             1      stevy                 1.0
2             2  BetterBot                 3.0
3             2      Super                 1.0
4             3  BetterBot                 0.0
...         ...        ...                 ...
145541    72771   HastyBot                 1.0
145542    72772  BetterBot                 3.0
145543    72772  Gtowngrad                 1.0
145544    72773   HastyBot                 2.0
145545    72773      adola                 2.0

[145546 rows x 3 columns]

In [207]:
special_letter['count_letters_JQXZ'].value_counts()

2.0    56582
1.0    37568
3.0    34787
0.0     8983
4.0     7524
5.0       89
6.0       12
7.0        1
Name: count_letters_JQXZ, dtype: int64

In [208]:
data[data['game_id'] == 732]

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count
19978,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,1,BetterBot,ADEEPRY,8D,PAYED,28,28,Play,463.0,2082.0,5,0,0.0,0.0,0.0,0.0,0.0
19979,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,2,IlmanHaziq,CDEIJNU,9C,CINE,20,20,Play,271.0,1758.0,4,0,0.0,0.0,0.0,0.0,0.0
19980,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,3,BetterBot,EEIIORW,10F,WEIR,32,60,Play,463.0,2082.0,4,0,0.0,0.0,0.0,0.0,0.0
19981,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,4,IlmanHaziq,DDIJSTU,11D,JUST,34,54,Play,271.0,1758.0,4,0,1.0,0.0,0.0,0.0,1.0
19982,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,5,BetterBot,?ABEIOO,D11,.OE,20,80,Play,463.0,2082.0,2,0,0.0,0.0,0.0,0.0,0.0
19983,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,6,IlmanHaziq,ADDIIQS,14B,QADI,40,94,Play,271.0,1758.0,4,0,0.0,1.0,0.0,0.0,1.0
19984,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,7,IlmanHaziq,ADDIIQS,NaN,--,-40,54,Exchange,271.0,1758.0,0,0,NaN,NaN,NaN,NaN,NaN
19985,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,8,BetterBot,?ABGIOU,C13,BUG,20,100,Play,463.0,2082.0,3,0,0.0,0.0,0.0,0.0,0.0
19986,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,9,IlmanHaziq,ADDIIQS,J6,QADIS,47,101,Play,271.0,1758.0,5,0,0.0,1.0,0.0,0.0,1.0
19987,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,10,BetterBot,?AAINNO,15C,.OANNA,24,124,Play,463.0,2082.0,5,0,0.0,0.0,0.0,0.0,0.0
19988,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,11,IlmanHaziq,ADEIRTV,K5,VIE,25,126,Play,271.0,1758.0,3,0,0.0,0.0,0.0,0.0,0.0
19989,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,12,BetterBot,?AIIIIT,NaN,-III,0,124,Exchange,463.0,2082.0,0,0,NaN,NaN,NaN,NaN,NaN
19990,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,13,IlmanHaziq,ADGRSTX,14B,X.,18,144,Play,271.0,1758.0,1,0,0.0,0.0,1.0,0.0,1.0
19991,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,14,BetterBot,?AEIMRT,H1,MIgRATE.,83,207,Play,463.0,2082.0,7,1,0.0,0.0,0.0,0.0,0.0
19992,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,15,IlmanHaziq,ADGMRST,14H,MAD,14,158,Play,271.0,1758.0,3,0,0.0,0.0,0.0,0.0,0.0
19993,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,16,BetterBot,BCDHIRR,2G,B.RCH,18,225,Play,463.0,2082.0,4,0,0.0,0.0,0.0,0.0,0.0
19994,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,17,IlmanHaziq,AGIRRST,3K,AIR,11,169,Play,271.0,1758.0,3,0,0.0,0.0,0.0,0.0,0.0
19995,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,18,BetterBot,?DEIRTV,4A,DIVERTe.,76,301,Play,463.0,2082.0,7,1,0.0,0.0,0.0,0.0,0.0
19996,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,19,IlmanHaziq,EEGNRST,A4,.EETS,18,187,Play,271.0,1758.0,4,0,0.0,0.0,0.0,0.0,0.0
19997,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,20,BetterBot,AFGOOOU,E2,FO.GO,18,319,Play,463.0,2082.0,4,0,0.0,0.0,0.0,0.0,0.0
19998,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,21,IlmanHaziq,AEGINRZ,13I,ZINEG,74,261,Play,271.0,1758.0,5,0,0.0,0.0,0.0,1.0,1.0
19999,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,22,IlmanHaziq,AEGINRZ,NaN,--,-74,187,Exchange,271.0,1758.0,0,0,NaN,NaN,NaN,NaN,NaN
20000,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,23,BetterBot,AKOOOSU,NaN,-KOOOU,0,319,Exchange,463.0,2082.0,0,0,NaN,NaN,NaN,NaN,NaN
20001,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,24,IlmanHaziq,AEGINRZ,13I,ZINER,72,259,Play,271.0,1758.0,5,0,0.0,0.0,0.0,1.0,1.0
20002,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,25,IlmanHaziq,AEGINRZ,NaN,--,-72,187,Exchange,271.0,1758.0,0,0,NaN,NaN,NaN,NaN,NaN
20003,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,26,BetterBot,AELSTWY,C2,WA.Y,26,345,Play,463.0,2082.0,3,0,0.0,0.0,0.0,0.0,0.0
20004,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,27,IlmanHaziq,AEGINRZ,13I,ZINE,47,234,Play,271.0,1758.0,4,0,0.0,0.0,0.0,1.0,1.0
20005,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,28,BetterBot,ELLNOST,N3,STOLLEN,63,408,Play,463.0,2082.0,7,1,0.0,0.0,0.0,0.0,0.0
20006,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,29,IlmanHaziq,AEGIORU,O8,EUOI,20,254,Play,271.0,1758.0,4,0,0.0,0.0,0.0,0.0,0.0
20007,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,30,BetterBot,HKLOPTU,N11,HULK,27,435,Play,463.0,2082.0,4,0,0.0,0.0,0.0,0.0,0.0
20008,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,31,IlmanHaziq,AFGLNOR,O13,OAR,17,271,Play,271.0,1758.0,3,0,0.0,0.0,0.0,0.0,0.0
20009,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,32,BetterBot,OPT,L11,PO.T,12,447,Play,463.0,2082.0,3,0,0.0,0.0,0.0,0.0,0.0
20010,732,BetterBot,regular,STANDARD,0,2022-08-16 11:53:29,CSW21,1500,0,RATED,1,179.035252,33,BetterBot,NaN,NaN,(FGLN),16,463,End,463.0,2082.0,0,0,NaN,NaN,NaN,NaN,NaN

### Rack used rate

In [209]:
data['rack_len'] = data.apply(lambda row: len(str(row['rack'])) if row['turn_type'] == 'Play' else 0, axis=1)
data

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count,rack_len
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0,3,0,0.0,0.0,0.0,0.0,0.0,7
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0,4,0,0.0,0.0,0.0,0.0,0.0,7
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0,6,0,0.0,0.0,0.0,0.0,0.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0,2,0,0.0,0.0,0.0,0.0,0.0,7
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,6
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0,3,0,0.0,0.0,0.0,0.0,0.0,5
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,3
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0,0,0,NaN,NaN,NaN,NaN,NaN,0

In [210]:
data['rack_used_rate'] = data['word_len'] / data['rack_len']
data

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count,rack_len,rack_used_rate
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0,6,0,0.0,0.0,0.0,0.0,0.0,7,0.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,6,0.500000
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0,3,0,0.0,0.0,0.0,0.0,0.0,5,0.600000
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,3,1.000000
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN

In [211]:
rack_used = data.groupby(['game_id', 'nickname'])['rack_used_rate'].mean().reset_index()
rack_used

        game_id   nickname  rack_used_rate
0             1  BetterBot        0.596154
1             1      stevy        0.569231
2             2  BetterBot        0.617063
3             2      Super        0.623377
4             3  BetterBot        0.547619
...         ...        ...             ...
145541    72771   HastyBot        0.517857
145542    72772  BetterBot        0.540816
145543    72772  Gtowngrad        0.485714
145544    72773   HastyBot        0.598901
145545    72773      adola        0.585714

[145546 rows x 3 columns]

In [212]:
rack_used[rack_used['rack_used_rate'] == 1]

        game_id nickname  rack_used_rate
78589     39295    budak             1.0
108175    54088  Zooglea             1.0

In [213]:
data[data['game_id'] == 39295]

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count,rack_len,rack_used_rate
1082444,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,1,budak,ELOPRSU,H4,PROULES,74,74,Play,0.0,1901.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082445,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,2,budak,ELOPRSU,NaN,--,-74,0,Exchange,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082446,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,3,HastyBot,EFGINNS,8D,FENINGS,80,80,Play,859.0,2214.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082447,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,4,budak,ELOPRSU,D3,PROSE.UL,76,76,Play,0.0,1901.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082448,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,5,budak,ELOPRSU,NaN,--,-76,0,Exchange,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082449,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,6,HastyBot,EEOORRR,D3,REROO.,18,98,Play,859.0,2214.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
1082450,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,7,budak,ELOPRSU,2B,LEPROUS,84,84,Play,0.0,1901.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082451,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,8,budak,ELOPRSU,NaN,--,-84,0,Exchange,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082452,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,9,HastyBot,DEEEERT,C1,TEERED,25,123,Play,859.0,2214.0,6,0,0.0,0.0,0.0,0.0,0.0,7,0.857143
1082453,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,10,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082454,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,11,HastyBot,AAEMORT,1C,.ERATOMA,83,206,Play,859.0,2214.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082455,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,12,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082456,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,13,HastyBot,AEIJLMT,J6,JI.M,29,235,Play,859.0,2214.0,3,0,1.0,0.0,0.0,0.0,1.0,7,0.428571
1082457,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,14,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082458,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,15,HastyBot,ABEFILT,2F,BEFIT,43,278,Play,859.0,2214.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
1082459,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,16,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082460,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,17,HastyBot,?AAALWZ,E3,AWA,27,305,Play,859.0,2214.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1082461,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,18,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082462,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,19,HastyBot,?AILOYZ,F6,ZA.ILY,40,345,Play,859.0,2214.0,5,0,0.0,0.0,0.0,1.0,1.0,7,0.714286
1082463,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,20,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082464,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,21,HastyBot,??ACKOU,11A,bUCKA.rO,80,425,Play,859.0,2214.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082465,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,22,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082466,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,23,HastyBot,CDNSUUV,H10,V.DUNS,36,461,Play,859.0,2214.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
1082467,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,24,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082468,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,25,HastyBot,ABCEEOU,3I,BEAU,22,483,Play,859.0,2214.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
1082469,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,26,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082470,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,27,HastyBot,CEGNOQV,L1,VO.GE,26,509,Play,859.0,2214.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
1082471,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,28,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082472,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,29,HastyBot,CILNQRT,B10,Q.ILT,68,577,Play,859.0,2214.0,4,0,0.0,1.0,0.0,0.0,1.0,7,0.571429
1082473,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,30,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082474,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,31,HastyBot,CENNRST,G4,CRET.N,27,604,Play,859.0,2214.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
1082475,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,32,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082476,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,33,HastyBot,AGIIINS,14G,I.SIGNIA,72,676,Play,859.0,2214.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
1082477,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,34,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082478,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,35,HastyBot,ADINPTY,K5,YAD,36,712,Play,859.0,2214.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1082479,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,36,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082480,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,37,HastyBot,HHINPTX,M3,TIX,50,762,Play,859.0,2214.0,3,0,0.0,0.0,1.0,0.0,1.0,7,0.428571
1082481,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,38,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082482,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,39,HastyBot,EHHLNOP,H4,HEP,39,801,Play,859.0,2214.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1082483,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,40,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082484,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,41,HastyBot,DHLNOOW,M12,WH.D,22,823,Play,859.0,2214.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1082485,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,42,budak,ELOPRSU,NaN,-,0,0,Pass,0.0,1901.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
1082486,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,43,HastyBot,LNOO,L9,NOLO,18,841,Play,859.0,2214.0,4,0,0.0,0.0,0.0,0.0,0.0,4,1.000000
1082487,39295,budak,rapid,STANDARD,0,2022-08-29 01:33:41,CSW21,720,0,RATED,1,48.609844,44,HastyBot,NaN,NaN,(ELOPRSU),18,859,End,859.0,2214.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN

### fisrt is Bot

In [214]:
first_bot = data.groupby(['game_id', 'nickname'])['first'].apply(lambda x: int(any(x.str.contains('Bot', case=True, regex=True)))).reset_index()

#data['first_Bot'] = data['first'].str.contains('Bot', case=True, regex=True).astype(int)

In [215]:
first_bot.rename(columns={'first': 'Bot_first'}, inplace=True)
first_bot

        game_id   nickname  Bot_first
0             1  BetterBot          1
1             1      stevy          1
2             2  BetterBot          0
3             2      Super          0
4             3  BetterBot          1
...         ...        ...        ...
145541    72771   HastyBot          1
145542    72772  BetterBot          0
145543    72772  Gtowngrad          0
145544    72773   HastyBot          1
145545    72773      adola          1

[145546 rows x 3 columns]

In [216]:
first_bot['Bot_first'].sum()

71722

In [217]:
data['first'].str.contains('Bot').sum()

986787

### Merge data

In [218]:
data_merge = pd.merge(data_merge, avg_bingo, on=["game_id", 'nickname'], how="inner")
data_merge = pd.merge(data_merge, avg_word_len, on=["game_id", 'nickname'], how="inner")
data_merge = pd.merge(data_merge, special_letter, on=["game_id", 'nickname'], how="inner")
data_merge = pd.merge(data_merge, rack_used, on=["game_id", 'nickname'], how="inner")
data_merge = pd.merge(data_merge, first_bot, on=["game_id", 'nickname'], how="inner")

In [219]:
data_merge

,game_id,nickname,turns_count,max_point,min_point,avg_bingo,word_len,count_letters_JQXZ,rack_used_rate,Bot_first
0,1,BetterBot,13,68,8,0.076923,4.000000,3.0,0.596154,1
1,1,stevy,13,98,2,0.142857,3.357143,1.0,0.569231,1
2,2,BetterBot,12,85,8,0.250000,4.250000,3.0,0.617063,0
3,2,Super,13,94,0,0.214286,3.428571,1.0,0.623377,0
4,3,BetterBot,13,76,0,0.076923,3.538462,0.0,0.547619,1
...,...,...,...,...,...,...,...,...,...,...
145541,72771,HastyBot,15,93,0,0.133333,3.333333,1.0,0.517857,1
145542,72772,BetterBot,14,81,9,0.142857,3.785714,3.0,0.540816,0
145543,72772,Gtowngrad,15,67,4,0.125000,2.812500,1.0,0.485714,0
145544,72773,HastyBot,13,39,4,0.000000,3.571429,2.0,0.598901,1
145545,72773,adola,12,90,5,0.166667,4.000000,2.0,0.585714,1

### winner Bot

In [220]:
data.head(60)

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count,rack_len,rack_used_rate
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0,6,0,0.0,0.0,0.0,0.0,0.0,7,0.857143
5,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,6,stevy,EEOORSX,M11,OXO,31,65,Play,429.0,1500.0,3,0,0.0,0.0,1.0,0.0,1.0,7,0.428571
6,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,7,BetterBot,AAEJRSU,5E,RAJAS,29,83,Play,335.0,1637.0,5,0,1.0,0.0,0.0,0.0,1.0,7,0.714286
7,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,8,stevy,AEEFIRS,9B,FAERIES,72,137,Play,429.0,1500.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
8,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,9,BetterBot,ELNNORU,C3,NEURON.L,68,151,Play,335.0,1637.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
9,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,10,stevy,EEEHIKO,6F,HO,35,172,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
10,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,11,BetterBot,EEGIQTW,B2,QI,24,175,Play,335.0,1637.0,2,0,0.0,1.0,0.0,0.0,1.0,7,0.285714
11,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,12,stevy,?EEEIKV,8A,KE.,26,198,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
12,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,13,BetterBot,BEEGITW,N13,WEB,21,196,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
13,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,14,stevy,??DEEIV,O8,rElIVED,98,296,Play,429.0,1500.0,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
14,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,15,BetterBot,EGILPTT,M3,TIP,17,213,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
15,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,16,stevy,BCEIITU,15L,CU.,10,306,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
16,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,17,BetterBot,EGLTTWY,3A,W..GLET,12,225,Play,335.0,1637.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
17,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,18,stevy,ABEIIRT,2F,BAITER,28,334,Play,429.0,1500.0,6,0,0.0,0.0,0.0,0.0,0.0,7,0.857143
18,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,19,BetterBot,MNOSSTY,N2,MOSSY,48,273,Play,335.0,1637.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
19,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,20,stevy,AAFINNR,1G,FAIN,37,371,Play,429.0,1500.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
20,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,21,BetterBot,ANOOTYZ,O1,NAY,28,301,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
21,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,22,stevy,ADENNRR,7B,D.NNA,19,390,Play,429.0,1500.0,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
22,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,23,BetterBot,GIOOTVZ,E9,.ITZ,26,327,Play,335.0,1637.0,3,0,0.0,0.0,0.0,1.0,1.0,7,0.428571
23,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,24,stevy,ELORR,12C,RE.,24,414,Play,429.0,1500.0,2,0,0.0,0.0,0.0,0.0,0.0,5,0.400000
24,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,25,BetterBot,GOOV,8K,V.GO.,8,335,Play,335.0,1637.0,3,0,0.0,0.0,0.0,0.0,0.0,4,0.750000
25,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,26,stevy,LOR,K12,LOR,13,427,Play,429.0,1500.0,3,0,0.0,0.0,0.0,0.0,0.0,3,1.000000
26,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,27,stevy,NaN,NaN,(O),2,429,End,429.0,1500.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
27,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,1,Super,AFINRTV,8D,FAINT,24,24,Play,NaN,NaN,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
28,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,2,BetterBot,EEEEGIT,G6,GE.IE,8,8,Play,NaN,NaN,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
29,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,3,Super,AAERTVW,F10,WAVER,34,58,Play,NaN,NaN,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
30,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,4,BetterBot,EEHNNOT,14B,ENTH.ONE,72,80,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
31,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,5,Super,AABEFTY,15G,FY,44,102,Play,NaN,NaN,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
32,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,6,BetterBot,DEOPPST,J8,STOPPED,85,165,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
33,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,7,Super,AABCDET,K10,BEAD,33,135,Play,NaN,NaN,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
34,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,8,BetterBot,DEIJNNR,E4,NINJ.,24,189,Play,NaN,NaN,4,0,1.0,0.0,0.0,0.0,1.0,7,0.571429
35,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,9,Super,ACEGIST,L6,CAGIEST,94,229,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
36,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,10,BetterBot,ADEOOQR,8L,.OOD,18,207,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
37,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,11,Super,HIILMNX,M12,HIM,25,254,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
38,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,12,BetterBot,AELQRRZ,5D,Q.,11,218,Play,NaN,NaN,1,0,0.0,1.0,0.0,0.0,1.0,7,0.142857
39,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,13,Super,DIILMNX,11C,LIM.,12,266,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
40,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,14,BetterBot,AEILRRZ,D8,.LA.R,16,234,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
41,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,15,Super,ADEILNX,15A,AX,36,302,Play,NaN,NaN,2,0,0.0,0.0,1.0,0.0,1.0,7,0.285714
42,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,16,BetterBot,BEIORRZ,N8,.RZO,33,267,Play,NaN,NaN,3,0,0.0,0.0,0.0,1.0,1.0,7,0.428571
43,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,17,Super,CDEEILN,O1,DECLINE.,89,391,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
44,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,18,BetterBot,ABEGIIR,6A,BEGI.,21,288,Play,NaN,NaN,4,0,0.0,0.0,0.0,0.0,0.0,7,0.571429
45,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,19,Super,?AOOUUV,NaN,-OOUUV,0,391,Exchange,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
46,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,20,BetterBot,?AIRSUY,A6,.URY,27,315,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
47,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,21,Super,?AAKSTW,6G,.AWK,22,413,Play,NaN,NaN,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
48,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,22,BetterBot,?AILSUU,4E,.AUtILUS,64,379,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
49,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,23,Super,?AOORST,NaN,-,0,413,Pass,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
50,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,24,BetterBot,EORTUV,2J,OEUVR.,22,401,Play,NaN,NaN,5,0,0.0,0.0,0.0,0.0,0.0,6,0.833333
51,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,25,Super,?AOORST,1D,RATOOnS,73,486,Play,NaN,NaN,7,1,0.0,0.0,0.0,0.0,0.0,7,1.000000
52,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,26,Super,NaN,NaN,(T),2,488,End,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
53,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,1,BetterBot,AJNOPQS,NaN,-JQ,0,0,Exchange,318.0,2071.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN
54,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,2,davidavid,EHIIRTY,8D,THEIR,18,18,Play,440.0,1811.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
55,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,3,BetterBot,ANNOOPS,E8,.OOP,18,18,Play,318.0,2071.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
56,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,4,davidavid,?AAIILY,F10,YA,30,48,Play,440.0,1811.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714
57,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,5,BetterBot,AHLNNST,12A,HALTS,34,52,Play,318.0,2071.0,5,0,0.0,0.0,0.0,0.0,0.0,7,0.714286
58,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,6,davidavid,?AAEIIL,A12,.AIL,21,69,Play,440.0,1811.0,3,0,0.0,0.0,0.0,0.0,0.0,7,0.428571
59,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262,7,BetterBot,GILNNNO,11E,..NGOLIN,22,74,Play,318.0,2071.0,6,0,0.0,0.0,0.0,0.0,0.0,7,0.857143

### Win and game by created_at

In [221]:
data['win'] = np.where((data['winner'] == 1) & data['nickname'].str.contains('Bot') | ((data['winner'] == 0) & ~data['nickname'].str.contains('Bot')), 0, 1)

In [222]:
data.tail()

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating,word_len,bingo,J_count,Q_count,X_count,Z_count,total_count,rack_len,rack_used_rate,win
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play,383.0,2075.0,2,0,0.0,0.0,0.0,0.0,0.0,7,0.285714,1
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,6,0.500000,0
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play,383.0,2075.0,3,0,0.0,0.0,0.0,0.0,0.0,5,0.600000,1
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play,346.0,2302.0,3,0,0.0,0.0,0.0,0.0,0.0,3,1.000000,0
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End,346.0,2302.0,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [223]:
win_data = data[['game_id', 'nickname', 'created_at', 'win']]

In [224]:
win_data = win_data.drop_duplicates()
win_data

         game_id   nickname           created_at  win
0              1  BetterBot  2022-08-26 03:38:49    0
1              1      stevy  2022-08-26 03:38:49    1
27             2      Super  2022-08-10 19:19:59    1
28             2  BetterBot  2022-08-10 19:19:59    0
53             3  BetterBot  2022-09-04 08:04:27    0
...          ...        ...                  ...  ...
2005412    72771       BB-8  2022-09-19 03:28:44    0
2005442    72772  Gtowngrad  2022-08-31 15:57:38    0
2005443    72772  BetterBot  2022-08-31 15:57:38    1
2005472    72773   HastyBot  2022-08-27 09:13:08    0
2005473    72773      adola  2022-08-27 09:13:08    1

[145546 rows x 4 columns]

In [225]:
win_data['game'] = win_data.sort_values(by=['created_at'], ascending=False).groupby('nickname').cumcount() + 1

In [226]:
win_data

         game_id   nickname           created_at  win   game
0              1  BetterBot  2022-08-26 03:38:49    0  12306
1              1      stevy  2022-08-26 03:38:49    1    297
27             2      Super  2022-08-10 19:19:59    1     99
28             2  BetterBot  2022-08-10 19:19:59    0  18862
53             3  BetterBot  2022-09-04 08:04:27    0   8714
...          ...        ...                  ...  ...    ...
2005412    72771       BB-8  2022-09-19 03:28:44    0    817
2005442    72772  Gtowngrad  2022-08-31 15:57:38    0     64
2005443    72772  BetterBot  2022-08-31 15:57:38    1  10214
2005472    72773   HastyBot  2022-08-27 09:13:08    0  22596
2005473    72773      adola  2022-08-27 09:13:08    1     59

[145546 rows x 5 columns]

### Merge together

In [227]:
data_merge = pd.merge(data_merge, win_data, on=["game_id", 'nickname'], how="inner")

In [228]:
data_merge

,game_id,nickname,turns_count,max_point,min_point,avg_bingo,word_len,count_letters_JQXZ,rack_used_rate,Bot_first,created_at,win,game
0,1,BetterBot,13,68,8,0.076923,4.000000,3.0,0.596154,1,2022-08-26 03:38:49,0,12306
1,1,stevy,13,98,2,0.142857,3.357143,1.0,0.569231,1,2022-08-26 03:38:49,1,297
2,2,BetterBot,12,85,8,0.250000,4.250000,3.0,0.617063,0,2022-08-10 19:19:59,0,18862
3,2,Super,13,94,0,0.214286,3.428571,1.0,0.623377,0,2022-08-10 19:19:59,1,99
4,3,BetterBot,13,76,0,0.076923,3.538462,0.0,0.547619,1,2022-09-04 08:04:27,0,8714
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145541,72771,HastyBot,15,93,0,0.133333,3.333333,1.0,0.517857,1,2022-09-19 03:28:44,1,3805
145542,72772,BetterBot,14,81,9,0.142857,3.785714,3.0,0.540816,0,2022-08-31 15:57:38,1,10214
145543,72772,Gtowngrad,15,67,4,0.125000,2.812500,1.0,0.485714,0,2022-08-31 15:57:38,0,64
145544,72773,HastyBot,13,39,4,0.000000,3.571429,2.0,0.598901,1,2022-08-27 09:13:08,0,22596
145545,72773,adola,12,90,5,0.166667,4.000000,2.0,0.585714,1,2022-08-27 09:13:08,1,59

### Merge train and test data

In [229]:
data_merge_all = pd.merge(data_merge, train_test_merge, on=["game_id", 'nickname'], how="inner")

In [230]:
data_merge_all

,game_id,nickname,turns_count,max_point,min_point,avg_bingo,word_len,count_letters_JQXZ,rack_used_rate,Bot_first,created_at,win,game,score,rating
0,1,BetterBot,13,68,8,0.076923,4.000000,3.0,0.596154,1,2022-08-26 03:38:49,0,12306,335.0,1637.0
1,1,stevy,13,98,2,0.142857,3.357143,1.0,0.569231,1,2022-08-26 03:38:49,1,297,429.0,1500.0
2,2,BetterBot,12,85,8,0.250000,4.250000,3.0,0.617063,0,2022-08-10 19:19:59,0,18862,401.0,2000.0
3,2,Super,13,94,0,0.214286,3.428571,1.0,0.623377,0,2022-08-10 19:19:59,1,99,488.0,NaN
4,3,BetterBot,13,76,0,0.076923,3.538462,0.0,0.547619,1,2022-09-04 08:04:27,0,8714,318.0,2071.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145541,72771,HastyBot,15,93,0,0.133333,3.333333,1.0,0.517857,1,2022-09-19 03:28:44,1,3805,393.0,1614.0
145542,72772,BetterBot,14,81,9,0.142857,3.785714,3.0,0.540816,0,2022-08-31 15:57:38,1,10214,442.0,1674.0
145543,72772,Gtowngrad,15,67,4,0.125000,2.812500,1.0,0.485714,0,2022-08-31 15:57:38,0,64,388.0,1364.0
145544,72773,HastyBot,13,39,4,0.000000,3.571429,2.0,0.598901,1,2022-08-27 09:13:08,0,22596,346.0,2302.0
145545,72773,adola,12,90,5,0.166667,4.000000,2.0,0.585714,1,2022-08-27 09:13:08,1,59,383.0,2075.0

### Transform to game level data frame

In [231]:
def col_trans(data):
    # Create a new column 'Bot_nickname' based on the condition
    data['Bot_nickname'] = data['nickname'].apply(lambda x: x if 'Bot' in x else None)
    # Create a new column 'Player_nickname' based on the condition
    data['Player_nickname'] = data['nickname'].apply(lambda x: x if 'Bot' not in x else None)
    
    # Create new columns with default value of 0
    columns_to_transform = ['turns_count', 'max_point', 'min_point', 'avg_bingo', 'word_len', 'count_letters_JQXZ', 'rack_used_rate', 'win', 'game', 'rating', 'score']
    
    for col in columns_to_transform:
        # Update 'Bot_{col}' based on 'Bot_nickname'
        data[f'Bot_{col}'] = data.groupby(['game_id', 'Bot_nickname'])[col].transform(lambda x: x.iloc[0] if not x.isnull().all() else np.nan)
        
        # Update 'Player_{col}' based on 'Player_nickname'
        data[f'Player_{col}'] = data.groupby(['game_id', 'Player_nickname'])[col].transform(lambda x: x.iloc[0] if not x.isnull().all() else np.nan)
    
    # Drop unnecessary columns
    data = data.drop(['nickname'] + columns_to_transform, axis=1)
    
    # Aggregate data by game_id
    aggregated_data = data.groupby('game_id').agg({
        'Bot_nickname': 'first',
        'Player_nickname': 'first',
        'Bot_turns_count': 'sum',
        'Player_turns_count': 'sum',
        'Bot_max_point': 'sum',
        'Player_max_point': 'sum',
        'Bot_min_point': 'sum',
        'Player_min_point': 'sum',
        'Bot_avg_bingo': 'sum',
        'Player_avg_bingo': 'sum',
        'Bot_word_len': 'sum',
        'Player_word_len': 'sum',
        'Bot_count_letters_JQXZ': 'sum',
        'Player_count_letters_JQXZ': 'sum',
        'Bot_rack_used_rate': 'sum',
        'Player_rack_used_rate': 'sum',
        'Bot_win': 'sum',
        'Player_win': 'sum',
        'Bot_game': 'sum',
        'Player_game': 'sum',
        'Bot_score' : 'sum',
        'Player_score' : 'sum',
        'Bot_rating' : 'sum',
        'Player_rating' : 'sum',
    }).reset_index()

    return aggregated_data

In [232]:
data_matix = col_trans(data_merge_all)

In [233]:
data_matix

,game_id,Bot_nickname,Player_nickname,Bot_turns_count,Player_turns_count,Bot_max_point,Player_max_point,Bot_min_point,Player_min_point,Bot_avg_bingo,Player_avg_bingo,Bot_word_len,Player_word_len,Bot_count_letters_JQXZ,Player_count_letters_JQXZ,Bot_rack_used_rate,Player_rack_used_rate,Bot_win,Player_win,Bot_game,Player_game,Bot_score,Player_score,Bot_rating,Player_rating
0,1,BetterBot,stevy,13.0,13.0,68.0,98.0,8.0,2.0,0.076923,0.142857,4.000000,3.357143,3.0,1.0,0.596154,0.569231,0.0,1.0,12306.0,297.0,335.0,429.0,1637.0,1500.0
1,2,BetterBot,Super,12.0,13.0,85.0,94.0,8.0,0.0,0.250000,0.214286,4.250000,3.428571,3.0,1.0,0.617063,0.623377,0.0,1.0,18862.0,99.0,401.0,488.0,2000.0,0.0
2,3,BetterBot,davidavid,13.0,13.0,76.0,103.0,0.0,13.0,0.076923,0.071429,3.538462,3.500000,0.0,3.0,0.547619,0.582418,0.0,1.0,8714.0,83.0,318.0,440.0,2071.0,1811.0
3,4,BetterBot,Inandoutworker,15.0,14.0,74.0,26.0,8.0,0.0,0.066667,0.000000,3.733333,1.357143,3.0,0.0,0.533333,0.226190,1.0,0.0,4883.0,122.0,478.0,119.0,1936.0,1473.0
4,5,STEEBot,stevy,15.0,15.0,81.0,51.0,14.0,0.0,0.133333,0.000000,3.866667,2.500000,1.0,3.0,0.566667,0.474490,1.0,0.0,8069.0,185.0,427.0,325.0,1844.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72768,72769,STEEBot,browndav,13.0,17.0,194.0,82.0,9.0,-78.0,0.230769,0.166667,4.153846,3.111111,3.0,1.0,0.593407,0.602041,1.0,0.0,7401.0,73.0,626.0,384.0,2110.0,0.0
72769,72770,HastyBot,samsiah06,16.0,16.0,106.0,24.0,9.0,-10.0,0.187500,0.000000,4.125000,1.750000,2.0,0.0,0.613095,0.268254,1.0,0.0,15269.0,14.0,590.0,97.0,2237.0,1332.0
72770,72771,HastyBot,BB-8,15.0,15.0,93.0,83.0,0.0,4.0,0.133333,0.062500,3.333333,2.937500,1.0,2.0,0.517857,0.506667,1.0,0.0,3805.0,817.0,393.0,390.0,1614.0,1500.0
72771,72772,BetterBot,Gtowngrad,14.0,15.0,81.0,67.0,9.0,4.0,0.142857,0.125000,3.785714,2.812500,3.0,1.0,0.540816,0.485714,1.0,0.0,10214.0,64.0,442.0,388.0,1674.0,1364.0
72772,72773,HastyBot,adola,13.0,12.0,39.0,90.0,4.0,5.0,0.000000,0.166667,3.571429,4.000000,2.0,2.0,0.598901,0.585714,0.0,1.0,22596.0,59.0,346.0,383.0,2302.0,2075.0

In [234]:
game_df = games.drop(['winner', 'created_at'], axis=1)

In [237]:
game_df

,game_id,first,time_control_name,game_end_reason,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds
0,1,BetterBot,regular,STANDARD,NWL20,1200,0,CASUAL,1,674.844274
1,2,Super,regular,STANDARD,CSW21,3600,0,RATED,1,364.214418
2,3,BetterBot,regular,STANDARD,CSW21,900,0,RATED,5,492.268262
3,4,BetterBot,regular,RESIGNED,CSW21,3600,0,CASUAL,1,350.861141
4,5,STEEBot,regular,STANDARD,NWL20,1200,0,CASUAL,1,642.688722
...,...,...,...,...,...,...,...,...,...,...
72768,72769,browndav,blitz,STANDARD,CSW21,180,0,RATED,1,218.043751
72769,72770,HastyBot,regular,TIME,CSW21,3600,0,RATED,1,3662.659287
72770,72771,HastyBot,regular,STANDARD,ECWL,900,0,CASUAL,10,236.133634
72771,72772,Gtowngrad,regular,STANDARD,NWL20,900,0,RATED,1,681.370077
72772,72773,HastyBot,regular,STANDARD,CSW21,1200,0,RATED,1,719.720262

### Final data!

In [238]:
final_data = pd.merge(game_df, data_matix, on=["game_id"], how="left")

In [239]:
final_data

,game_id,first,time_control_name,game_end_reason,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,Bot_nickname,Player_nickname,Bot_turns_count,Player_turns_count,Bot_max_point,Player_max_point,Bot_min_point,Player_min_point,Bot_avg_bingo,Player_avg_bingo,Bot_word_len,Player_word_len,Bot_count_letters_JQXZ,Player_count_letters_JQXZ,Bot_rack_used_rate,Player_rack_used_rate,Bot_win,Player_win,Bot_game,Player_game,Bot_score,Player_score,Bot_rating,Player_rating
0,1,BetterBot,regular,STANDARD,NWL20,1200,0,CASUAL,1,674.844274,BetterBot,stevy,13.0,13.0,68.0,98.0,8.0,2.0,0.076923,0.142857,4.000000,3.357143,3.0,1.0,0.596154,0.569231,0.0,1.0,12306.0,297.0,335.0,429.0,1637.0,1500.0
1,2,Super,regular,STANDARD,CSW21,3600,0,RATED,1,364.214418,BetterBot,Super,12.0,13.0,85.0,94.0,8.0,0.0,0.250000,0.214286,4.250000,3.428571,3.0,1.0,0.617063,0.623377,0.0,1.0,18862.0,99.0,401.0,488.0,2000.0,0.0
2,3,BetterBot,regular,STANDARD,CSW21,900,0,RATED,5,492.268262,BetterBot,davidavid,13.0,13.0,76.0,103.0,0.0,13.0,0.076923,0.071429,3.538462,3.500000,0.0,3.0,0.547619,0.582418,0.0,1.0,8714.0,83.0,318.0,440.0,2071.0,1811.0
3,4,BetterBot,regular,RESIGNED,CSW21,3600,0,CASUAL,1,350.861141,BetterBot,Inandoutworker,15.0,14.0,74.0,26.0,8.0,0.0,0.066667,0.000000,3.733333,1.357143,3.0,0.0,0.533333,0.226190,1.0,0.0,4883.0,122.0,478.0,119.0,1936.0,1473.0
4,5,STEEBot,regular,STANDARD,NWL20,1200,0,CASUAL,1,642.688722,STEEBot,stevy,15.0,15.0,81.0,51.0,14.0,0.0,0.133333,0.000000,3.866667,2.500000,1.0,3.0,0.566667,0.474490,1.0,0.0,8069.0,185.0,427.0,325.0,1844.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72768,72769,browndav,blitz,STANDARD,CSW21,180,0,RATED,1,218.043751,STEEBot,browndav,13.0,17.0,194.0,82.0,9.0,-78.0,0.230769,0.166667,4.153846,3.111111,3.0,1.0,0.593407,0.602041,1.0,0.0,7401.0,73.0,626.0,384.0,2110.0,0.0
72769,72770,HastyBot,regular,TIME,CSW21,3600,0,RATED,1,3662.659287,HastyBot,samsiah06,16.0,16.0,106.0,24.0,9.0,-10.0,0.187500,0.000000,4.125000,1.750000,2.0,0.0,0.613095,0.268254,1.0,0.0,15269.0,14.0,590.0,97.0,2237.0,1332.0
72770,72771,HastyBot,regular,STANDARD,ECWL,900,0,CASUAL,10,236.133634,HastyBot,BB-8,15.0,15.0,93.0,83.0,0.0,4.0,0.133333,0.062500,3.333333,2.937500,1.0,2.0,0.517857,0.506667,1.0,0.0,3805.0,817.0,393.0,390.0,1614.0,1500.0
72771,72772,Gtowngrad,regular,STANDARD,NWL20,900,0,RATED,1,681.370077,BetterBot,Gtowngrad,14.0,15.0,81.0,67.0,9.0,4.0,0.142857,0.125000,3.785714,2.812500,3.0,1.0,0.540816,0.485714,1.0,0.0,10214.0,64.0,442.0,388.0,1674.0,1364.0
72772,72773,HastyBot,regular,STANDARD,CSW21,1200,0,RATED,1,719.720262,HastyBot,adola,13.0,12.0,39.0,90.0,4.0,5.0,0.000000,0.166667,3.571429,4.000000,2.0,2.0,0.598901,0.585714,0.0,1.0,22596.0,59.0,346.0,383.0,2302.0,2075.0

### Historic performance (need to discuss)

In [372]:
first_10 = win_data[win_data['game'] <= 10]

In [373]:
first_10

         game_id     nickname           created_at  win  game
360           14   Anfield223  2022-09-14 14:06:24    0    10
981           37   derickalim  2022-09-18 13:22:05    1     1
1324          49        DJosh  2022-08-12 07:13:02    1     6
1570          58   eideticeve  2022-09-18 16:02:15    0     4
1593          59   audrey.lwx  2022-08-31 00:30:37    0     9
...          ...          ...                  ...  ...   ...
2004437    72736     patricck  2022-09-22 11:29:25    0     4
2004545    72740        cesar  2022-09-18 01:37:32    1    10
2004867    72752   mizhubbard  2022-09-15 03:13:28    0     8
2004982    72756  Basonomia28  2022-07-30 04:23:26    0     2
2005040    72758    Takahashi  2022-08-05 08:14:45    0     5

[9675 rows x 5 columns]

In [374]:
sum_first_10 = first_10.groupby('nickname')['win'].sum().reset_index()
sum_first_10.rename(columns={'win': 'win_10'}, inplace=True)
sum_first_10

        nickname  win_10
0     0188889876       0
1     0927399533       0
2              1       0
3      10IQPlays       0
4     171_selene       1
...          ...     ...
1466        zman       5
1467      zomban       0
1468    zugzwang       3
1469        zuzu       1
1470     zyzzyva       3

[1471 rows x 2 columns]

In [375]:
win_data = pd.merge(win_data, sum_first_10, on=["nickname"], how="left")

In [376]:
win_data

        game_id   nickname           created_at  win   game  win_10
0             1  BetterBot  2022-08-26 03:38:49    0  12306       6
1             1      stevy  2022-08-26 03:38:49    1    297       5
2             2      Super  2022-08-10 19:19:59    1     99       9
3             2  BetterBot  2022-08-10 19:19:59    0  18862       6
4             3  BetterBot  2022-09-04 08:04:27    0   8714       6
...         ...        ...                  ...  ...    ...     ...
145541    72771       BB-8  2022-09-19 03:28:44    0    817       3
145542    72772  Gtowngrad  2022-08-31 15:57:38    0     64       1
145543    72772  BetterBot  2022-08-31 15:57:38    1  10214       6
145544    72773   HastyBot  2022-08-27 09:13:08    0  22596       5
145545    72773      adola  2022-08-27 09:13:08    1     59       0

[145546 rows x 6 columns]

In [379]:
first_20 = win_data[win_data['game'] <= 20]
first_20

        game_id     nickname           created_at  win  game  win_10
15            8   AliSalman1  2022-09-06 21:03:24    0    11       5
17            9         cccc  2022-09-02 01:55:00    0    13       4
27           14   Anfield223  2022-09-14 14:06:24    0    10       1
58           30       ji1222  2022-09-15 21:23:57    0    18       1
65           33     Hercules  2022-09-08 05:34:09    1    14       4
...         ...          ...                  ...  ...   ...     ...
145511    72756  Basonomia28  2022-07-30 04:23:26    0     2       0
145515    72758    Takahashi  2022-08-05 08:14:45    0     5       4
145517    72759        wagyu  2022-08-29 01:00:35    1    16       4
145522    72762    kyjo55555  2022-08-24 11:16:15    1    16       4
145539    72770    samsiah06  2022-09-04 00:13:24    0    14       0

[15775 rows x 6 columns]

In [380]:
sum_first_20 = first_20.groupby('nickname')['win'].sum().reset_index()
sum_first_20.rename(columns={'win': 'win_20'}, inplace=True)
sum_first_20

        nickname  win_20
0     0188889876       0
1     0927399533       1
2              1       0
3      10IQPlays       0
4     171_selene       1
...          ...     ...
1466        zman       9
1467      zomban       0
1468    zugzwang       3
1469        zuzu       1
1470     zyzzyva       3

[1471 rows x 2 columns]

In [382]:
win_data = pd.merge(win_data, sum_first_20, on=["nickname"], how="left")

In [383]:
win_data

        game_id   nickname           created_at  win   game  win_10  win_20
0             1  BetterBot  2022-08-26 03:38:49    0  12306       6      12
1             1      stevy  2022-08-26 03:38:49    1    297       5       8
2             2      Super  2022-08-10 19:19:59    1     99       9      14
3             2  BetterBot  2022-08-10 19:19:59    0  18862       6      12
4             3  BetterBot  2022-09-04 08:04:27    0   8714       6      12
...         ...        ...                  ...  ...    ...     ...     ...
145541    72771       BB-8  2022-09-19 03:28:44    0    817       3      11
145542    72772  Gtowngrad  2022-08-31 15:57:38    0     64       1       3
145543    72772  BetterBot  2022-08-31 15:57:38    1  10214       6      12
145544    72773   HastyBot  2022-08-27 09:13:08    0  22596       5      11
145545    72773      adola  2022-08-27 09:13:08    1     59       0       3

[145546 rows x 7 columns]

In [384]:
win_data[win_data['nickname'] == 'zman'].sort_values('game')

        game_id nickname           created_at  win  game  win_10  win_20
123891    61946     zman  2022-08-28 00:55:15    1     1       5       9
46712     23357     zman  2022-08-27 18:41:48    1     2       5       9
145108    72555     zman  2022-08-10 23:08:20    1     3       5       9
12287      6144     zman  2022-08-06 04:01:44    0     4       5       9
6686       3344     zman  2022-08-06 03:59:42    0     5       5       9
135737    67869     zman  2022-08-06 03:57:55    1     6       5       9
60028     30015     zman  2022-08-06 03:55:04    0     7       5       9
24033     12017     zman  2022-08-06 03:50:08    0     8       5       9
93553     46777     zman  2022-08-06 00:03:12    0     9       5       9
67400     33701     zman  2022-08-05 23:51:06    1    10       5       9
114169    57085     zman  2022-08-05 23:39:25    1    11       5       9
15570      7786     zman  2022-08-05 23:25:59    1    12       5       9
92551     46276     zman  2022-08-05 23:17:24    0    13       5       9
14501      7251     zman  2022-08-01 07:10:30    1    14       5       9
76546     38274     zman  2022-08-01 06:51:54    1    15       5       9