In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
turns = pd.read_csv("turns.csv")

In [3]:
turns

,game_id,turn_number,nickname,rack,location,move,points,score,turn_type
0,1,1,BetterBot,DDEGITT,8G,DIG,10,10,Play
1,1,2,stevy,AEHOPUX,7H,HAP,18,18,Play
2,1,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play
3,1,4,stevy,EMORSUX,5K,UM,16,34,Play
4,1,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play
...,...,...,...,...,...,...,...,...,...
2005493,72773,22,adola,ABINRRU,15N,IN,18,376,Play
2005494,72773,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play
2005495,72773,24,adola,ABRRU,15E,BRA.,7,383,Play
2005496,72773,25,HastyBot,EIP,7A,PIE,11,342,Play
2005497,72773,26,HastyBot,NaN,NaN,(RU),4,346,End

In [4]:
turns.columns

Index(['game_id', 'turn_number', 'nickname', 'rack', 'location', 'move',
       'points', 'score', 'turn_type'],
      dtype='object')

In [5]:
games = pd.read_csv("games.csv")
games

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274
1,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418
2,3,BetterBot,regular,STANDARD,1,2022-09-04 08:04:27,CSW21,900,0,RATED,5,492.268262
3,4,BetterBot,regular,RESIGNED,0,2022-09-12 02:36:19,CSW21,3600,0,CASUAL,1,350.861141
4,5,STEEBot,regular,STANDARD,0,2022-09-06 04:31:36,NWL20,1200,0,CASUAL,1,642.688722
...,...,...,...,...,...,...,...,...,...,...,...,...
72768,72769,browndav,blitz,STANDARD,0,2022-09-07 13:24:13,CSW21,180,0,RATED,1,218.043751
72769,72770,HastyBot,regular,TIME,0,2022-09-04 00:13:24,CSW21,3600,0,RATED,1,3662.659287
72770,72771,HastyBot,regular,STANDARD,0,2022-09-19 03:28:44,ECWL,900,0,CASUAL,10,236.133634
72771,72772,Gtowngrad,regular,STANDARD,0,2022-08-31 15:57:38,NWL20,900,0,RATED,1,681.370077
72772,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262

In [6]:
games.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds'],
      dtype='object')

In [7]:
games_turns_merged = pd.merge(games, turns, on=["game_id"], how="left")

In [8]:
games_turns_merged.shape

(2005498, 20)

In [9]:
games_turns_merged.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds',
       'turn_number', 'nickname', 'rack', 'location', 'move', 'points',
       'score', 'turn_type'],
      dtype='object')

In [10]:
games_turns_merged.drop_duplicates()

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score,turn_type
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005493,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,22,adola,ABINRRU,15N,IN,18,376,Play
2005494,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,23,HastyBot,EGHIIP,H12,.HIG,24,331,Play
2005495,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,24,adola,ABRRU,15E,BRA.,7,383,Play
2005496,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,25,HastyBot,EIP,7A,PIE,11,342,Play
2005497,72773,HastyBot,regular,STANDARD,1,2022-08-27 09:13:08,CSW21,1200,0,RATED,1,719.720262,26,HastyBot,NaN,NaN,(RU),4,346,End

In [11]:
games_turns_merged.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds',
       'turn_number', 'nickname', 'rack', 'location', 'move', 'points',
       'score', 'turn_type'],
      dtype='object')

In [12]:
games_turns_merged.isnull().sum()

game_id                       0
first                         0
time_control_name             0
game_end_reason               0
winner                        0
created_at                    0
lexicon                       0
initial_time_seconds          0
increment_seconds             0
rating_mode                   0
max_overtime_minutes          0
game_duration_seconds         0
turn_number                   0
nickname                      0
rack                      69390
location                 132239
move                        454
points                        0
score                         0
turn_type                   395
dtype: int64

In [13]:
train = pd.read_csv("train.csv")

In [14]:
train

        game_id        nickname  score  rating
0             1       BetterBot    335    1637
1             1           stevy    429    1500
2             3       davidavid    440    1811
3             3       BetterBot    318    2071
4             4  Inandoutworker    119    1473
...         ...             ...    ...     ...
100815    72771        HastyBot    393    1614
100816    72772       BetterBot    442    1674
100817    72772       Gtowngrad    388    1364
100818    72773           adola    383    2075
100819    72773        HastyBot    346    2302

[100820 rows x 4 columns]

In [15]:
games_turns_merged_train = pd.merge(games_turns_merged, train, how="left", on = ["game_id", "nickname"])

In [16]:
games_turns_merged_train[games_turns_merged_train["game_id"] == 1]

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating
0,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,1,BetterBot,DDEGITT,8G,DIG,10,10,Play,335.0,1637.0
1,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,2,stevy,AEHOPUX,7H,HAP,18,18,Play,429.0,1500.0
2,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,3,BetterBot,DEELTTU,6I,LUTE,16,26,Play,335.0,1637.0
3,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,4,stevy,EMORSUX,5K,UM,16,34,Play,429.0,1500.0
4,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,5,BetterBot,ACDEITU,L5,..DICATE,28,54,Play,335.0,1637.0
5,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,6,stevy,EEOORSX,M11,OXO,31,65,Play,429.0,1500.0
6,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,7,BetterBot,AAEJRSU,5E,RAJAS,29,83,Play,335.0,1637.0
7,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,8,stevy,AEEFIRS,9B,FAERIES,72,137,Play,429.0,1500.0
8,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,9,BetterBot,ELNNORU,C3,NEURON.L,68,151,Play,335.0,1637.0
9,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,10,stevy,EEEHIKO,6F,HO,35,172,Play,429.0,1500.0
10,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,11,BetterBot,EEGIQTW,B2,QI,24,175,Play,335.0,1637.0
11,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,12,stevy,?EEEIKV,8A,KE.,26,198,Play,429.0,1500.0
12,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,13,BetterBot,BEEGITW,N13,WEB,21,196,Play,335.0,1637.0
13,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,14,stevy,??DEEIV,O8,rElIVED,98,296,Play,429.0,1500.0
14,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,15,BetterBot,EGILPTT,M3,TIP,17,213,Play,335.0,1637.0
15,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,16,stevy,BCEIITU,15L,CU.,10,306,Play,429.0,1500.0
16,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,17,BetterBot,EGLTTWY,3A,W..GLET,12,225,Play,335.0,1637.0
17,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,18,stevy,ABEIIRT,2F,BAITER,28,334,Play,429.0,1500.0
18,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,19,BetterBot,MNOSSTY,N2,MOSSY,48,273,Play,335.0,1637.0
19,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,20,stevy,AAFINNR,1G,FAIN,37,371,Play,429.0,1500.0
20,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,21,BetterBot,ANOOTYZ,O1,NAY,28,301,Play,335.0,1637.0
21,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,22,stevy,ADENNRR,7B,D.NNA,19,390,Play,429.0,1500.0
22,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,23,BetterBot,GIOOTVZ,E9,.ITZ,26,327,Play,335.0,1637.0
23,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,24,stevy,ELORR,12C,RE.,24,414,Play,429.0,1500.0
24,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,25,BetterBot,GOOV,8K,V.GO.,8,335,Play,335.0,1637.0
25,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,26,stevy,LOR,K12,LOR,13,427,Play,429.0,1500.0
26,1,BetterBot,regular,STANDARD,1,2022-08-26 03:38:49,NWL20,1200,0,CASUAL,1,674.844274,27,stevy,NaN,NaN,(O),2,429,End,429.0,1500.0

In [17]:
games_turns_merged_train[games_turns_merged_train["game_id"] == 2]

,game_id,first,time_control_name,game_end_reason,winner,created_at,lexicon,initial_time_seconds,increment_seconds,rating_mode,max_overtime_minutes,game_duration_seconds,turn_number,nickname,rack,location,move,points,score_x,turn_type,score_y,rating
27,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,1,Super,AFINRTV,8D,FAINT,24,24,Play,NaN,NaN
28,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,2,BetterBot,EEEEGIT,G6,GE.IE,8,8,Play,NaN,NaN
29,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,3,Super,AAERTVW,F10,WAVER,34,58,Play,NaN,NaN
30,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,4,BetterBot,EEHNNOT,14B,ENTH.ONE,72,80,Play,NaN,NaN
31,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,5,Super,AABEFTY,15G,FY,44,102,Play,NaN,NaN
32,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,6,BetterBot,DEOPPST,J8,STOPPED,85,165,Play,NaN,NaN
33,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,7,Super,AABCDET,K10,BEAD,33,135,Play,NaN,NaN
34,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,8,BetterBot,DEIJNNR,E4,NINJ.,24,189,Play,NaN,NaN
35,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,9,Super,ACEGIST,L6,CAGIEST,94,229,Play,NaN,NaN
36,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,10,BetterBot,ADEOOQR,8L,.OOD,18,207,Play,NaN,NaN
37,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,11,Super,HIILMNX,M12,HIM,25,254,Play,NaN,NaN
38,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,12,BetterBot,AELQRRZ,5D,Q.,11,218,Play,NaN,NaN
39,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,13,Super,DIILMNX,11C,LIM.,12,266,Play,NaN,NaN
40,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,14,BetterBot,AEILRRZ,D8,.LA.R,16,234,Play,NaN,NaN
41,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,15,Super,ADEILNX,15A,AX,36,302,Play,NaN,NaN
42,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,16,BetterBot,BEIORRZ,N8,.RZO,33,267,Play,NaN,NaN
43,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,17,Super,CDEEILN,O1,DECLINE.,89,391,Play,NaN,NaN
44,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,18,BetterBot,ABEGIIR,6A,BEGI.,21,288,Play,NaN,NaN
45,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,19,Super,?AOOUUV,NaN,-OOUUV,0,391,Exchange,NaN,NaN
46,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,20,BetterBot,?AIRSUY,A6,.URY,27,315,Play,NaN,NaN
47,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,21,Super,?AAKSTW,6G,.AWK,22,413,Play,NaN,NaN
48,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,22,BetterBot,?AILSUU,4E,.AUtILUS,64,379,Play,NaN,NaN
49,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,23,Super,?AOORST,NaN,-,0,413,Pass,NaN,NaN
50,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,24,BetterBot,EORTUV,2J,OEUVR.,22,401,Play,NaN,NaN
51,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,25,Super,?AOORST,1D,RATOOnS,73,486,Play,NaN,NaN
52,2,Super,regular,STANDARD,1,2022-08-10 19:19:59,CSW21,3600,0,RATED,1,364.214418,26,Super,NaN,NaN,(T),2,488,End,NaN,NaN

In [18]:
check  = games_turns_merged_train[games_turns_merged_train["rating"].isnull()==True]

In [19]:
check.groupby(["game_id"])["turn_number"].count().reset_index().min()

game_id         2
turn_number    21
dtype: int64

In [20]:
test = pd.read_csv("test.csv")
test

       game_id    nickname  score  rating
0            2       Super    488     NaN
1            2   BetterBot    401  2000.0
2            7     STEEBot    377  2082.0
3            7      Priya1    379     NaN
4           11     STEEBot    334  1829.0
...        ...         ...    ...     ...
44721    72762   kyjo55555    367     NaN
44722    72768    HastyBot    524  2356.0
44723    72768  Maximilian    357     NaN
44724    72769     STEEBot    626  2110.0
44725    72769    browndav    384     NaN

[44726 rows x 4 columns]

In [21]:
submission = pd.read_csv("test.csv")
test

       game_id    nickname  score  rating
0            2       Super    488     NaN
1            2   BetterBot    401  2000.0
2            7     STEEBot    377  2082.0
3            7      Priya1    379     NaN
4           11     STEEBot    334  1829.0
...        ...         ...    ...     ...
44721    72762   kyjo55555    367     NaN
44722    72768    HastyBot    524  2356.0
44723    72768  Maximilian    357     NaN
44724    72769     STEEBot    626  2110.0
44725    72769    browndav    384     NaN

[44726 rows x 4 columns]

In [22]:
games_turns_merged_train.columns

Index(['game_id', 'first', 'time_control_name', 'game_end_reason', 'winner',
       'created_at', 'lexicon', 'initial_time_seconds', 'increment_seconds',
       'rating_mode', 'max_overtime_minutes', 'game_duration_seconds',
       'turn_number', 'nickname', 'rack', 'location', 'move', 'points',
       'score_x', 'turn_type', 'score_y', 'rating'],
      dtype='object')

In [23]:
1/0

ZeroDivisionError: division by zero

In [25]:
temp = games_turns_merged_train[games_turns_merged_train["game_id"] == 1]

In [26]:
board = [['' for _ in range(15)] for _ in range(15)]
board

[['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
 ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '']]

In [27]:
for i, row in temp.dropna().iterrows():
    move = row['move']
    loc = row['location']

    col_index = ''.join([char for char in loc if char.isalpha()])
    row_index = ''.join([str(int(char)) for char in loc if char.isdigit()])
    
    if loc[0].isdigit():
        fill = "across"
    else:
        fill = "vertical"

    print(f"move: {move}, location: {loc}, col_index: {col_index}, row_index: {row_index}, fill : {fill}")

move: DIG, location: 8G, col_index: G, row_index: 8, fill : across
move: HAP, location: 7H, col_index: H, row_index: 7, fill : across
move: LUTE, location: 6I, col_index: I, row_index: 6, fill : across
move: UM, location: 5K, col_index: K, row_index: 5, fill : across
move: ..DICATE, location: L5, col_index: L, row_index: 5, fill : vertical
move: OXO, location: M11, col_index: M, row_index: 11, fill : vertical
move: RAJAS, location: 5E, col_index: E, row_index: 5, fill : across
move: FAERIES, location: 9B, col_index: B, row_index: 9, fill : across
move: NEURON.L, location: C3, col_index: C, row_index: 3, fill : vertical
move: HO, location: 6F, col_index: F, row_index: 6, fill : across
move: QI, location: B2, col_index: B, row_index: 2, fill : vertical
move: KE., location: 8A, col_index: A, row_index: 8, fill : across
move: WEB, location: N13, col_index: N, row_index: 13, fill : vertical
move: rElIVED, location: O8, col_index: O, row_index: 8, fill : vertical
move: TIP, location: M3, col_index: M, row_index: 3, fill : vertical
move: CU., location: 15L, col_index: L, row_index: 15, fill : across
move: W..GLET, location: 3A, col_index: A, row_index: 3, fill : across
move: BAITER, location: 2F, col_index: F, row_index: 2, fill : across
move: MOSSY, location: N2, col_index: N, row_index: 2, fill : vertical
move: FAIN, location: 1G, col_index: G, row_index: 1, fill : across
move: NAY, location: O1, col_index: O, row_index: 1, fill : vertical
move: D.NNA, location: 7B, col_index: B, row_index: 7, fill : across
move: .ITZ, location: E9, col_index: E, row_index: 9, fill : vertical
move: RE., location: 12C, col_index: C, row_index: 12, fill : across
move: V.GO., location: 8K, col_index: K, row_index: 8, fill : across
move: LOR, location: K12, col_index: K, row_index: 12, fill : vertical

In [28]:
board = [['' for _ in range(15)] for _ in range(15)]

for i, row in temp.dropna().iterrows():
    move = row['move']
    loc = row['location']

    col_index = ''.join([char for char in loc if char.isalpha()])
    row_index = ''.join([str(int(char)) for char in loc if char.isdigit()])

    fill = "across" if loc[0].isdigit() else "vertical"

    if fill == "across":
        for j, letter in enumerate(move):
            board[int(row_index) - 1][ord(col_index) - ord('A') + j] = letter
    else:
        for j, letter in enumerate(move):
            board[int(row_index) + j - 1][ord(col_index) - ord('A')] = letter

# Display the filled board in a grid
for row in board:
    print('\t'.join(row))

						F	A	I	N					N
	Q				B	A	I	T	E	R			M	A
W	.	.	G	L	E	T						T	O	Y
		E										I	S
		U		R	A	J	A	S		U	.	P	S
		R			H	O		L	U	T	.		Y
	D	.	N	N	A		H	A	P		D
K	E	.				D	I	G		V	.	G	O	.
	F	.	E	.	I	E	S				C			E
		L		I							A			l
				T							T	O		I
		R	E	.						L	E	X		V
										O		O	W	E
										R			E	D
											C	U	.

In [29]:
board

[['', '', '', '', '', '', 'F', 'A', 'I', 'N', '', '', '', '', 'N'],
 ['', 'Q', '', '', '', 'B', 'A', 'I', 'T', 'E', 'R', '', '', 'M', 'A'],
 ['W', '.', '.', 'G', 'L', 'E', 'T', '', '', '', '', '', 'T', 'O', 'Y'],
 ['', '', 'E', '', '', '', '', '', '', '', '', '', 'I', 'S', ''],
 ['', '', 'U', '', 'R', 'A', 'J', 'A', 'S', '', 'U', '.', 'P', 'S', ''],
 ['', '', 'R', '', '', 'H', 'O', '', 'L', 'U', 'T', '.', '', 'Y', ''],
 ['', 'D', '.', 'N', 'N', 'A', '', 'H', 'A', 'P', '', 'D', '', '', ''],
 ['K', 'E', '.', '', '', '', 'D', 'I', 'G', '', 'V', '.', 'G', 'O', '.'],
 ['', 'F', '.', 'E', '.', 'I', 'E', 'S', '', '', '', 'C', '', '', 'E'],
 ['', '', 'L', '', 'I', '', '', '', '', '', '', 'A', '', '', 'l'],
 ['', '', '', '', 'T', '', '', '', '', '', '', 'T', 'O', '', 'I'],
 ['', '', 'R', 'E', '.', '', '', '', '', '', 'L', 'E', 'X', '', 'V'],
 ['', '', '', '', '', '', '', '', '', '', 'O', '', 'O', 'W', 'E'],
 ['', '', '', '', '', '', '', '', '', '', 'R', '', '', 'E', 'D'],
 ['', '', '', '', '', '', '', '', '', '', '', 'C', 'U', '.', '']]

In [ ]:
1/0

In [ ]:
import pandas as pd

def calculate_word_length_average(temp):
    total_words = 0
    total_word_length = 0

    for _, row in temp.iterrows():
        move = str(row['move'])  # Ensure the 'move' column is treated as a string

        # Split the move into words based on '.'
        words = move.split('.')
        
        # Calculate word length and update totals
        for word in words:
            if word:
                total_words += 1
                total_word_length += len(word)

    if total_words == 0:
        return 0

    return total_word_length / total_words

# Assuming 'game_df' is your DataFrame with the provided data
word_length_average = calculate_word_length_average(temp)
print(f'Word Length Average: {word_length_average:.2f}')

How to handle dots is key. Need it clarified

what to do with dots? or any other symbol.

In [ ]:
def calculate_rack_usage_percentage(game_df):
    total_rack_letters = 0
    used_rack_letters = 0

    for _, row in game_df.iterrows():
        rack = str(row['rack'])  # Ensure the 'rack' column is treated as a string
        move = str(row['move'])  # Ensure the 'move' column is treated as a string

        # Count total rack letters
        total_rack_letters += len(rack)

        # Count used rack letters based on the move
        for letter in move:
            if letter != '.':
                used_rack_letters += 1

    if total_rack_letters == 0:
        return 0

    return (used_rack_letters / total_rack_letters) * 100

rank_usage = calculate_rack_usage_percentage(temp)
print(f'Rack Usage: {rank_usage:.2f}%')

In [ ]:
import pandas as pd

def calculate_high_scoring_letter_usage(temp):
    """Calculates the frequency of using high-scoring letters (Q, Z, J, X) in the DataFrame."""
    high_scoring_letter_count = 0
    total_letters = 0

    for _, row in temp.iterrows():
        move = str(row['move'])  # Ensure the 'move' column is treated as a string

        # Count high-scoring letters in the move
        high_scoring_letter_count += sum(1 for letter in move if letter in ['Q', 'Z', 'J', 'X'])
        
        # Count total letters in the move
        total_letters += len(move)

    if total_letters == 0:
        return 0

    return (high_scoring_letter_count / total_letters) * 100

# Assuming 'game_df' is your DataFrame with the provided data
high_scoring_letter_usage = calculate_high_scoring_letter_usage(temp)
print(f'High-Scoring Letter Usage: {high_scoring_letter_usage:.2f}%')